swagger:
  resourcePackage: io.arlas.server.rest
zipkin:
  enabled: false
  # Listening IP address of the service
  # serviceHost: 127.0.0.1
  # Listening port of the service
  # servicePort: 9999
  # collector: http
  # baseUrl: http://localhost:9411/
server:
  #requestLog:
  #  appenders:
  #    - type: file
  #      currentLogFilename: ${ACCESS_LOG_DIR:-log}/access.log
  #      archivedLogFilenamePattern: ${ACCESS_LOG_DIR:-log}/our-app/accedd-%d.log.gz
  registerDefaultExceptionMappers: false
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 9999
logging:
  level: INFO
elastic-host: localhost
elastic-port: 9300
arlas-index: .arlas
