###################
# PACKAGING STAGE #
###################
FROM gisaia/arlas-openjdk-17-distroless:20260128085401

# application placed into /opt/app
WORKDIR /opt/app
COPY arlas-server/target/arlas-server*.jar /opt/app/arlas-server.jar
COPY conf/configuration.yaml /opt/app/configuration.yaml
EXPOSE 9999

ENV JDK_JAVA_OPTIONS="-Xmx1g -XX:+ExitOnOutOfMemoryError"
CMD ["arlas-server.jar", "server", "/opt/app/configuration.yaml"]

