version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.0.1}
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.seed_hosts=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    volumes:
#      - /var/lib/elasticsearch:/usr/share/elasticsearch/data
      - ${ELASTIC_DATADIR}:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
      - 19300:9300
