###################
# PACKAGING STAGE #
###################
FROM gisaia/arlas-openjdk-17-distroless:20250830104345

# application placed into /opt/app
WORKDIR /opt/app
COPY arlas-server/target/arlas-server*.jar /opt/app/arlas-server.jar
COPY conf/configuration.yaml /opt/app/configuration.yaml
EXPOSE 9999

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl http://localhost:9999/admin/healthcheck | grep -v "\"healthy\":false" || exit 1

ENV JDK_JAVA_OPTIONS="-Xmx512m -XX:+ExitOnOutOfMemoryError"
CMD ["arlas-server.jar", "server", "/opt/app/configuration.yaml"]

