version: "3"
# docker-compose -f docker-compose-postgis.yml up -d
# docker-compose -f docker-compose-postgis.yml down -v
services:
  postgis:
    container_name: postgis
    restart: unless-stopped
    image: postgis/postgis:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
    volumes:
    #- /home/user/projects/postgis/data:/var/lib/postgresql/data
    - ${PG_DATADIR}:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tech@gisaia.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "8080:80"
    volumes:
    # on your local host: chmod -R 777 /home/user/projects/postgis/pgadmin
    #- /home/user/projects/postgis/pgadmin/servers.json:/pgadmin4/servers.json
    #- /home/user/projects/postgis/pgadmin/data:/var/lib/pgadmin
    - ${PGA_CONFIG}:/pgadmin4/servers.json
    - ${PGA_DATADIR}:/var/lib/pgadmin
