version: '3'

services:
  arlas-server:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile-package-only}
    image: gisaia/arlas-server:${ARLAS_VERSION:-latest}
    container_name: arlas-server
    environment:
      - ARLAS_ELASTIC_CLUSTER="docker-cluster"
      - ARLAS_ELASTIC_NODES=elasticsearch:9300
      - ARLAS_PREFIX="${ARLAS_PREFIX:-/arlas}"
      - ARLAS_APP_PATH="${ARLAS_APP_PATH:-/}"
      - ARLAS_BASE_URI="${ARLAS_BASE_URI:-http://arlas-server:9999/arlas/}"
      - ARLAS_SERVICE_WFS_ENABLE="${ARLAS_SERVICE_WFS_ENABLE:-false}"
      - ARLAS_INSPIRE_ENABLED="${ARLAS_INSPIRE_ENABLED:-false}"
      - ARLAS_SERVICE_CSW_ENABLE="${ARLAS_SERVICE_CSW_ENABLE:-false}"
      - ARLAS_SERVICE_TAG_ENABLE="${ARLAS_SERVICE_TAG_ENABLE:-false}"
      - ARLAS_SERVICE_RASTER_TILES_ENABLE="${ARLAS_SERVICE_RASTER_TILES_ENABLE:-false}"
    ports:
      - 19999:9999
    command: ["/opt/app/wait-for-elasticsearch.sh"]
