version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ports:
      - 19200:9200
      - 19300:9300
  arlas-server:
    image: arlas-server:${ARLAS_VERSION}
    container_name: arlas-server
    environment:
      - "ARLAS_ELASTIC_CLUSTER=docker-cluster"
      - "ARLAS_ELASTIC_HOST=elasticsearch"
    ports:
      - 19999:9999
    command: ["/opt/app/wait-for-elasticsearch.sh", "elasticsearch", "9300"]
