version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-6.2.3}
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ports:
      - 19200:9200
      - 19300:9300
  arlas-server:
    build:
      context: .
      dockerfile: Dockerfile-package-only
    image: arlas-server:${ARLAS_VERSION:-latest}
    container_name: arlas-server
    environment:
      - "ARLAS_ELASTIC_CLUSTER=docker-cluster"
      - "ARLAS_ELASTIC_HOST=elasticsearch"
      - "ARLAS_SERVICE_WFS_ENABLE=true"
      - "ARLAS_PREFIX=${ARLAS_PREFIX:-/arlas}"
      - "ARLAS_APP_PATH=${ARLAS_APP_PATH:-/}"
      - "ARLAS_OGC_SERVER_URI=${ARLAS_OGC_SERVER_URI:-http://arlas-server:9999/arlas/}"
    ports:
      - 19999:9999
    command: ["/opt/app/wait-for-elasticsearch.sh", "elasticsearch", "9300"]
