###################
# PACKAGING STAGE #
###################
FROM gisaia/arlas-openjdk:8-jre-alpine

# install script dependencies
RUN apk add --update netcat-openbsd curl && rm -rf /var/cache/apk/*

# application placed into /opt/app
WORKDIR /opt/app
ADD arlas-server/target/arlas-server*.jar /opt/app/arlas-server.jar
ADD conf/configuration.yaml /opt/app/configuration.yaml
ADD docker-resources/wait-for-elasticsearch.sh /opt/app/wait-for-elasticsearch.sh
ADD docker-resources/start.sh /opt/app/start.sh
EXPOSE 9999

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl http://localhost:9999/admin/healthcheck | grep -v "\"healthy\":false" || exit 1

CMD /opt/app/start.sh
