###################
# PACKAGING STAGE #
###################
FROM openjdk:8-jre-alpine

# install script dependencies
RUN apk add --update bash netcat-openbsd curl && rm -rf /var/cache/apk/*

# application placed into /opt/app
WORKDIR /opt/app
ADD arlas-tagger/target/arlas-tagger*.jar /opt/app/arlas-tagger.jar
ADD conf/configuration.yaml /opt/app/configuration.yaml
ADD scripts/wait-for-tagger-deps.sh /opt/app/wait-for-tagger-deps.sh
ADD scripts/start-tagger.sh /opt/app/start-tagger.sh
EXPOSE 9999

ENTRYPOINT ["bash", "-c"]
CMD /opt/app/start-tagger.sh
