version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: "zookeeper"
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: "kafka"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      LOG4J_LOGGER_KAFKA: INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-6.6.2}
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    volumes:
      - /var/lib/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
      - 19300:9300
  arlas-server:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile-package-only}
    image: arlas-server:${ARLAS_VERSION:-latest}
    container_name: arlas-server
    environment:
      - ARLAS_ELASTIC_CLUSTER="docker-cluster"
      - ARLAS_ELASTIC_NODES=elasticsearch:9300
      - ARLAS_PREFIX="${ARLAS_PREFIX:-/arlas}"
      - ARLAS_APP_PATH="${ARLAS_APP_PATH:-/}"
      - ARLAS_BASE_URI="${ARLAS_BASE_URI:-http://arlas-server:9999/arlas/}"
      - ARLAS_SERVICE_WFS_ENABLE="${ARLAS_SERVICE_WFS_ENABLE:-false}"
      - ARLAS_INSPIRE_ENABLED="${ARLAS_INSPIRE_ENABLED:-false}"
      - ARLAS_SERVICE_CSW_ENABLE="${ARLAS_SERVICE_CSW_ENABLE:-false}"
      - ARLAS_SERVICE_TAG_ENABLE="${ARLAS_SERVICE_TAG_ENABLE:-false}"
      - ARLAS_SERVICE_RASTER_TILES_ENABLE="${ARLAS_SERVICE_RASTER_TILES_ENABLE:-false}"
    ports:
      - 19999:9999
    command: ["/opt/app/wait-for-elasticsearch.sh"]
  arlas-tagger:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile-package-only-tagger}
    image: arlas-tagger:${ARLAS_VERSION:-latest}
    container_name: arlas-tagger
    environment:
      - ARLAS_ELASTIC_CLUSTER="docker-cluster"
      - ARLAS_ELASTIC_NODES=elasticsearch:9300
      - ARLAS_PREFIX="${ARLAS_PREFIX:-/arlas}"
      - ARLAS_APP_PATH="${ARLAS_APP_PATH:-/}"
      - ARLAS_BASE_URI="${ARLAS_BASE_URI:-http://arlas-tagger:9999/arlas/}"
      - ARLAS_SERVICE_EXPLORE_ENABLE=false
      - KAFKA_BATCH_SIZE="${KAFKA_BATCH_SIZE:-10}"
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:9092}
      - KAFKA_CONSUMER_GROUP_ID_TAGREF_LOG="${KAFKA_CONSUMER_GROUP_ID_TAGREF_LOG:-tagref_log_consumer_group}"
      - KAFKA_CONSUMER_GROUP_ID_EXECUTE_TAGS="${KAFKA_CONSUMER_GROUP_ID_EXECUTE_TAGS:-execute_tags_consumer_group}"
      - KAFKA_TOPIC_TAGREF_LOG="${KAFKA_TOPIC_TAGREF_LOG:-tagref_log}"
      - KAFKA_TOPIC_EXECUTE_TAGS="${KAFKA_TOPIC_EXECUTE_TAGS:-execute_tags}"
    ports:
      - 29999:9999
    command: ["/opt/app/wait-for-tagger-deps.sh $$KAFKA_BROKERS $$ARLAS_ELASTIC_NODES"]
