########################################################
############ SWAGGER                     ###############
########################################################
#
swagger: # Configuration of SWAGGER for generating documentation and APIs
  resourcePackage: io.arlas.server.rest # The java package to process for extracting the APIs
  # temporary patch for bug https://github.com/smoketurner/dropwizard-swagger/issues/206
  # to be removed when version of dropwizard.swagger.version is upgraded
  customJavascript: ${ARLAS_CUSTOM_JS:-/arlas/swagger-static/custom-request-interceptor.js}


########################################################
############ ENABLED SERVICES            ###############
########################################################
#
arlas-service-collections-enabled: ${ARLAS_SERVICE_COLLECTIONS_ENABLE:-true}
arlas-service-explore-enabled: ${ARLAS_SERVICE_EXPLORE_ENABLE:-true}
arlas-service-opensearch-enabled: ${ARLAS_SERVICE_OPENSEARCH_ENABLE:-true}
arlas-service-wfs-enabled: ${ARLAS_SERVICE_WFS_ENABLE:-false}
arlas-service-csw-enabled: ${ARLAS_SERVICE_CSW_ENABLE:-false}
arlas-service-raster-tiles-enabled: ${ARLAS_SERVICE_RASTER_TILES_ENABLE:-true}

########################################################
############ HTTP SERVER                 ###############
########################################################
# Configuration of the HTTP Server and of the HTTP ACCESS LOGGING
server:
  requestLog:
    appenders:
      - type: console
      - type: file
        currentLogFilename: ${ARLAS_ACCESS_LOG_FILE:-arlas-access.log}
        archivedLogFilenamePattern: ${ACCESS_LOG_FILE_ARCHIVE:-arlas-access-%d.log.gz}
  registerDefaultExceptionMappers: false
  type: simple
  rootPath: ${ARLAS_PREFIX:-/arlas}
  applicationContextPath: ${ARLAS_APP_PATH:-/}
  adminContextPath: ${ARLAS_ADMIN_PATH:-/admin}
  connector:
    type: http
    port: ${ARLAS_PORT:-9999}
    maxRequestHeaderSize: 8KiB
  maxThreads: ${ARLAS_MAX_THREADS:-1024}
  minThreads: ${ARLAS_MIN_THREADS:-8}
  maxQueuedRequests: ${ARLAS_MAX_QUEUED_REQUESTS:-1024}

########################################################
############ URL Masking                 ###############
########################################################
arlas-base-uri: ${ARLAS_BASE_URI:-''}

########################################################
############ LOGGING                     ###############
########################################################
# Configuration console and file LOGGING
logging:
  level: ${ARLAS_LOGGING_LEVEL:-INFO}
  loggers:
    "org.apache.http": ${ARLAS_LOGGING_APACHE_HTTP_LEVEL:-INFO}
    "org.eclipse.jetty": ${ARLAS_LOGGING_JETTY_LEVEL:-INFO}
    "org.elasticsearch.client": ${ARLAS_LOGGING_ELASTICSEARCH_LEVEL:-DEBUG}
    "org.reflections": ${ARLAS_LOGGING_REFLECTIONS_LEVEL:-INFO}
    "org.glassfish": ${ARLAS_LOGGING_GLASSFISH_LEVEL:-INFO}
    "io.dropwizard": ${ARLAS_LOGGING_DROPWIZARD_LEVEL:-INFO}
    "io.swagger": ${ARLAS_LOGGING_SWAGGER_LEVEL:-INFO}
    "javax.management.mbeanserver": ${ARLAS_LOGGING_MBEAN_LEVEL:-INFO}
    "com.hazelcast": ${ARLAS_LOGGING_HAZELCAST_LEVEL:-INFO}
  appenders:
    - type: console
      threshold:  ${ARLAS_LOGGING_CONSOLE_LEVEL:-INFO}
    - type: file
      currentLogFilename: ${ARLAS_LOGGING_FILE:-arlas.log}
      threshold: ${ARLAS_LOGGING_FILE_LEVEL:-INFO}
      archive: ${ARLAS_LOGGING_FILE_ARCHIVE:-true}
      archivedLogFilenamePattern: ${ARLAS_LOGGING_FILE_ARCHIVE_FILE_PATTERN:-arlas-%d.log}
      archivedFileCount: ${ARLAS_LOGGING_FILE_ARCHIVE_FILE_COUNT:-5}

########################################################
############ DATASOURCE                  ###############
########################################################
# Configuration of the datasource
arlas-index:  ${ARLAS_ELASTIC_INDEX:-.arlas}
elastic:
  elastic-nodes: ${ARLAS_ELASTIC_NODES:-localhost:9200}
  elastic-sniffing: ${ARLAS_ELASTIC_SNIFFING:-false}
  elastic-enable-ssl: ${ARLAS_ELASTIC_ENABLE_SSL:-false}
  elastic-credentials: ${ARLAS_ELASTIC_CREDENTIALS}
  elastic-skip-master: ${ARLAS_ELASTIC_SKIP_MASTER:-true}

########################################################
############ CACHE                       ###############
########################################################
# Configuration of the cache
#arlas_cache_factory_class: ${ARLAS_CACHE_FACTORY_CLASS:-io.arlas.commons.cache.NoCacheFactory}
arlas_cache_factory_class: ${ARLAS_CACHE_FACTORY_CLASS:-io.arlas.server.core.impl.cache.HazelcastCacheFactory}
arlas-cache-size: ${ARLAS_CACHE_SIZE:-1000}
arlas-cache-timeout: ${ARLAS_CACHE_TIMEOUT:-300}
arlas-rest-cache-timeout: ${ARLAS_REST_CACHE_TIMEOUT:-0}

########################################################
############ COLLECTION DISCOVERY        ###############
########################################################
# Automatic discovery of the collections contained in the datasource (ES).
# Set schedule to 0 if you want to disable the automatic discovery
collection-auto-discover:
  preferred-id-field-name: id,identifier
  preferred-timestamp-field-name: params.startdate
  preferred-centroid-field-name: geo_params.centroid
  preferred-geometry-field-name: geo,geo_params.geometry
  preferred-h3-field-name: geo_params.h3
  schedule: ${ARLAS_COLLECTION_AUTODISCOVER_SCHEDULE:-0} # Set to 0 to disable the discovery

########################################################
############ ZIPKIN                      ###############
########################################################
# Zipkin let you analyze the API calls
zipkin: # The ZIPIN configuration, not active by default
  enabled: ${ARLAS_ZIPKIN_ENABLED:-false} # Do we want zipkin to collect the API calls? Not by default.
  serviceHost: ${ARLAS_ZIPKIN_SERVICE_HOST:-127.0.0.1} # Listening IP address of the service
  servicePort: ${ARLAS_PORT:-9999} # Listening port of the service
  collector: ${ARLAS_ZIPKIN_COLLECTOR:-http}
  baseUrl: ${ARLAS_ZIPKIN_BASEURL:-http://localhost:9411} # Where is zipkin running?

########################################################
############ WFS                         ###############
########################################################
arlas-wfs:
  featureNamespace: ${ARLAS_WFS_FEATURE_NAMESPACE:-arlas}

arlas-ogc:
  serviceProviderName: ${ARLAS_OGC_SERVICE_PROVIDER_NAME:-ARLAS}
  serviceProviderSite: ${ARLAS_OGC_SERVICE_PROVIDER_SITE:-www.gisaia.com}
  serviceProviderRole: ${ARLAS_OGC_SERVICE_PROVIDER_ROLE:-Developer}
  serviceContactIndividualName: ${ARLAS_OGC_SERVICE_CONTACT_NAME:-Gisaïa}
  serviceContactMail: ${ARLAS_OGC_SERVICE_CONTACT_MAIL:-contact@gisaia.com}
  serviceContactAdressCity: ${ARLAS_OGC_SERVICE_CONTACT_CITY:-Toulouse}
  serviceContactAdressPostalCode: ${ARLAS_OGC_SERVICE_CONTACT_CODE:-31000}
  serviceContactAdressCountry: ${ARLAS_OGC_SERVICE_CONTACT_COUNTRY:-France}
  queryMaxFeature: ${ARLAS_OGC_QUERY_MAX_FEATURE:-1000}

arlas-csw:
  serviceIdentificationTitle: ${ARLAS_CSW_TITLE:-Discovery Service - CSW}
  serviceIdentificationAbstract: ${ARLAS_CSW_ABSTRACT:-Discovery Service - CSW}
  serviceIdentificationLanguage: ${ARLAS_CSW_LANGUAGE:-eng}
  openSearchDescription: ${ARLAS_CSW_OPENSEARCH_DESCRIPTION:-Geo-BigData Collection Catalog}
  openSearchShortName: ${ARLAS_CSW_OPENSEARCH_SHORTNAME:-Geo-Catalog}

arlas-inspire:
  enabled: ${ARLAS_INSPIRE_ENABLED:-false}
  services_date_of_creation: ${ARLAS_INSPIRE_SERVICES_DATE_OF_CREATION:-2018-11-05} # YYYY-MM-DD
  access_and_use_conditions: ${ARLAS_INSPIRE_ACCESS_AND_USE_CONDITIONS:-no conditions apply} # Free text or specify a URL to a link that describes eventual conditions
  public_access_limitations: ${ARLAS_INSPIRE_PUBLIC_ACCESS_LIMITATIONS:-no limitations apply} # Free text or specify a URL to a link that describes eventual limitations

arlas_service_stac_enabled: ${ARLAS_SERVICE_STAC_ENABLE:-true}
arlas_stac:
  stac_version: ${ARLAS_STAC_VERSION:-1.0.0}
  type: ${ARLAS_STAC_TYPE:-Catalog}
  id: ${ARLAS_STAC_ID:-arlas}
  title: ${ARLAS_STAC_TITLE:-Arlas Exploration}
  description: ${ARLAS_STAC_DESCRIPTION:-Catalog for Arlas Exploration items}
  conforms_to:
    - https://api.stacspec.org/v1.0.0/core
    - https://api.stacspec.org/v1.0.0/item-search
    - https://api.stacspec.org/v1.0.0/ogcapi-features
    - https://api.stacspec.org/v1.0.0/collections
    - http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core
    - http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30
#   - http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson
    - https://api.stacspec.org/v1.0.0/item-search#sort
    - https://api.stacspec.org/v1.0.0/item-search#context
#   - https://api.stacspec.org/v1.0.0/item-search#fields
#   - https://api.stacspec.org/v1.0.0/item-search#filter

arlas_cors:
  enabled: ${ARLAS_CORS_ENABLED:-false}
  allowed_origins: ${ARLAS_CORS_ALLOWED_ORIGINS:-"*"}
  allowed_headers: ${ARLAS_CORS_ALLOWED_HEADERS:-"arlas-user,arlas-groups,arlas-organization,X-Requested-With,Content-Type,Accept,Origin,Authorization,X-Forwarded-User"}
  allowed_methods: ${ARLAS_CORS_ALLOWED_METHODS:-"OPTIONS,GET,PUT,POST,DELETE,HEAD"}
  allowed_credentials: ${ARLAS_CORS_ALLOWED_CREDENTIALS:-true}
  exposed_headers: ${ARLAS_CORS_EXPOSED_HEADERS:-"Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin,Location,WWW-Authenticate"}

arlas_database_factory_class: ${ARLAS_DATABASE_FACTORY_CLASS:-io.arlas.server.impl.ElasticDatabaseToolsFactory}

########################################################
############ AUTHENTICATION              ###############
########################################################
arlas_auth_policy_class: ${ARLAS_AUTH_POLICY_CLASS:-io.arlas.filter.impl.NoPolicyEnforcer}
arlas_auth_column_filter_required: ${ARLAS_AUTH_COLUMN_FILTER_REQUIRED:-false}

arlas_auth:
  permission_url: ${ARLAS_AUTH_PERMISSION_URL:-http://arlas-iam-server/arlas_iam_server/auth/permissions}
  public_uris: [${ARLAS_AUTH_PUBLIC_URIS:-swagger.*:*}]
  # deprecated, use it only for Integration tests
  certificate_file: ${ARLAS_AUTH_CERT_FILE:-/opt/app/arlas.pem}
  certificate_url: ${ARLAS_AUTH_CERT_URL:-}
  header_user: ${ARLAS_HEADER_USER:-arlas-user}
  header_group: ${ARLAS_HEADER_GROUP:-arlas-groups}
  claim_roles: ${ARLAS_CLAIM_ROLES:-http://arlas.io/roles}
  claim_permissions: ${ARLAS_CLAIM_PERMISSIONS:-http://arlas.io/permissions}
  keycloak:
    realm: ${ARLAS_AUTH_KEYCLOAK_REALM:-arlas}
    auth-server-url: ${ARLAS_AUTH_KEYCLOAK_URL:-http://keycloak:8080/auth}
    resource: ${ARLAS_AUTH_KEYCLOAK_RESOURCE:-arlas}
    credentials:
      secret: ${ARLAS_AUTH_KEYCLOAK_SECRET:-2ec98d5c-7a6d-4f7f-9214-99d0a4ba3907}
