########################################################
############ SWAGGER                     ###############
########################################################
#
swagger: # Configuration of SWAGGER for generating documentation and APIs
  resourcePackage: io.arlas.server.rest # The java package to process for extracting the APIs



########################################################
############ ENABLED SERVICES            ###############
########################################################
#
arlas-service-collections-enabled: ${ARLAS_SERVICE_COLLECTIONS_ENABLE:-true}
arlas-service-explore-enabled: ${ARLAS_SERVICE_EXPLORE_ENABLE:-true}
arlas-service-opensearch-enabled: ${ARLAS_SERVICE_OPENSEARCH_ENABLE:-true}
arlas-service-wfs-enabled: ${ARLAS_SERVICE_WFS_ENABLE:-false}
arlas-service-csw-enabled: ${ARLAS_SERVICE_CSW_ENABLE:-false}
arlas-service-tag-enabled: ${ARLAS_SERVICE_TAG_ENABLE:-false}
arlas-service-raster-tiles-enabled: ${ARLAS_SERVICE_RASTER_TILES_ENABLE:-true}

########################################################
############ HTTP SERVER                 ###############
########################################################
# Configuration of the HTTP Server and of the HTTP ACCESS LOGGING
server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ${ARLAS_ACCESS_LOG_FILE:-arlas-access.log}
        archivedLogFilenamePattern: ${ACCESS_LOG_FILE_ARCHIVE:-arlas-access-%d.log.gz}
  registerDefaultExceptionMappers: false
  type: simple
  rootPath: ${ARLAS_PREFIX:-/arlas}
  applicationContextPath: ${ARLAS_APP_PATH:-/}
  adminContextPath: ${ARLAS_ADMIN_PATH:-/admin}
  connector:
    type: http
    port: ${ARLAS_PORT:-9999}
  maxThreads: ${ARLAS_MAX_THREADS:-1024}
  minThreads: ${ARLAS_MIN_THREADS:-8}
  maxQueuedRequests: ${ARLAS_MAX_QUEUED_REQUESTS:-1024}

########################################################
############ LOGGING                     ###############
########################################################
# Configuration console and file LOGGING
logging:
  level: ${ARLAS_LOGGING_LEVEL:-INFO}
  appenders:
    - type: console
      threshold:  ${ARLAS_LOGGING_CONSOLE_LEVEL:-INFO}
    - type: file
      currentLogFilename: ${ARLAS_LOGGING_FILE:-arlas.log}
      threshold: ${ARLAS_LOGGING_FILE_LEVEL:-INFO}
      archive: ${ARLAS_LOGGING_FILE_ARCHIVE:-true}
      archivedLogFilenamePattern: ${ARLAS_LOGGING_FILE_ARCHIVE_FILE_PATTERN:-arlas-%d.log}
      archivedFileCount: ${ARLAS_LOGGING_FILE_ARCHIVE_FILE_COUNT:-5}

########################################################
############ DATASOURCE                  ###############
########################################################
# Configuration of the datasource
elastic-nodes: ${ARLAS_ELASTIC_NODES:-localhost:9300}
elastic-sniffing: ${ARLAS_ELASTIC_SNIFFING:-false}
elastic-cluster: ${ARLAS_ELASTIC_CLUSTER:-elasticsearch}
arlas-index:  ${ARLAS_ELASTIC_INDEX:-.arlas}

########################################################
############ CACHE                       ###############
########################################################
# Configuration of the cache
arlas-cache-size: ${ARLAS_CACHE_SIZE:-1000}
arlas-cache-timeout: ${ARLAS_CACHE_TIMEOUT:-60}
arlas-cors-enabled: ${ARLAS_CORS_ENABLED:-true}

########################################################
############ COLLECTION DISCOVERY        ###############
########################################################
# Automatic discovery of the collections contained in the datasource (ES).
# Set schedule to 0 if you want to disable the automatic discovery
collection-auto-discover:
  preferred-id-field-name: id,identifier
  preferred-timestamp-field-name: params.startdate
  preferred-centroid-field-name: geo_params.centroid
  preferred-geometry-field-name: geo,geo_params.geometry
  schedule: ${ARLAS_COLLECTION_AUTODISCOVER_SCHEDULE:-0} # Set to 0 to disable the discovery

########################################################
############ ZIPKIN                      ###############
########################################################
# Zipkin let you analyze the API calls
zipkin: # The ZIPIN configuration, not active by default
  enabled: ${ARLAS_ZIPKIN_ENABLED:-false} # Do we want zipkin to collect the API calls? Not by default.
  serviceHost: ${ARLAS_ZIPKIN_SERVICE_HOST:-127.0.0.1} # Listening IP address of the service
  servicePort: ${ARLAS_PORT:-9999} # Listening port of the service
  collector: ${ARLAS_ZIPKIN_COLLECTOR:-http}
  baseUrl: ${ARLAS_ZIPKIN_BASEURL:-http://localhost:9411} # Where is zipkin running?

########################################################
############ WFS                      ###############
########################################################
arlas-wfs:
  featureNamespace: ${ARLAS_WFS_FEATURE_NAMESPACE:-arlas}
  replaceChar: ${ARLAS_WFS_REPLACE_CHAR:-_}

arlas-ogc:
  serverUri: ${ARLAS_OGC_SERVER_URI:-http://localhost:9999/arlas/}
  serviceProviderName: ${ARLAS_OGC_SERVICE_PROVIDER_NAME:-ARLAS}
  serviceProviderSite: ${ARLAS_OGC_SERVICE_PROVIDER_SITE:-www.gisaia.com}
  serviceProviderRole: ${ARLAS_OGC_SERVICE_PROVIDER_ROLE:-Developer}
  serviceContactIndividualName: ${ARLAS_OGC_SERVICE_CONTACT_NAME:-Gisaïa}
  serviceContactMail: ${ARLAS_OGC_SERVICE_CONTACT_MAIL:-contact@gisaia.com}
  serviceContactAdressCity: ${ARLAS_OGC_SERVICE_CONTACT_CITY:-Toulouse}
  serviceContactAdressPostalCode: ${ARLAS_OGC_SERVICE_CONTACT_CODE:-31000}
  serviceContactAdressCountry: ${ARLAS_OGC_SERVICE_CONTACT_COUNTRY:-France}
  queryMaxFeature: ${ARLAS_OGC_QUERY_MAX_FEATURE:-1000}

arlas-csw:
  serviceIdentificationTitle: ${ARLAS_CSW_TITLE:-Discovery Service - CSW}
  serviceIdentificationAbstract: ${ARLAS_CSW_ABSTRACT:-Discovery Service - CSW}
  serviceIdentificationLanguage: ${ARLAS_CSW_LANGUAGE:-eng}
  openSearchDescription: ${ARLAS_CSW_OPENSEARCH_DESCRIPTION:-Geo-BigData Collection Catalog}
  openSearchShortName: ${ARLAS_CSW_OPENSEARCH_SHORTNAME:-Geo-Catalog}

arlas-inspire:
  enabled: ${ARLAS_INSPIRE_ENABLED:-false}
  services_date_of_creation: ${ARLAS_INSPIRE_SERVICES_DATE_OF_CREATION:-2018-11-05} # YYYY-MM-DD
  access_and_use_conditions: ${ARLAS_INSPIRE_ACCESS_AND_USE_CONDITIONS:-no conditions apply} # Free text or specify a URL to a link that describes eventual conditions
  public_access_limitations: ${ARLAS_INSPIRE_PUBLIC_ACCESS_LIMITATIONS:-no limitations apply} # Free text or specify a URL to a link that describes eventual limitations
########################################################
############ OPENSEARCH                  ###############
########################################################
opensearch:
  url-template-prefix: ${ARLAS_OPENSEARCH_URL_TEMPLATE:-http://localhost:9999/arlas/explore/COLLECTION/_search} # If the placemark COLLECTION is specified in the url template, it will be replaced by the collection name in ARLAS server.