<?xml version="1.0" encoding="UTF-8"?>
<project
        xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.arlas</groupId>
        <artifactId>arlas-server-parent</artifactId>
        <version>28.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>arlas-tests</artifactId>
    <version>28.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>ARLAS server tests</name>
    <dependencies>
        <dependency>
            <groupId>io.arlas</groupId>
            <artifactId>arlas-server</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- ____________________________________________________ -->
        <!-- Tests -->
        <!-- ____________________________________________________ -->
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${io.rest-assured.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>