apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arlas-server.fullname" . }}
{{ include "arlas-server.namespace" . | indent 2 }}
  labels:
    app: {{ template "arlas-server.name" . }}
    chart: {{ template "arlas-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ int .Values.replicaCount }}
{{- include "arlas-server.revisionHistoryLimit" . | indent 2 }}
  selector:
    matchLabels:
      app: {{ template "arlas-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "arlas-server.name" . }}
        release: {{ .Release.Name }}
    spec:
{{include "arlas-server.imagePullSecrets" . | indent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: {{ int .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "{{ .Values.adminPath }}/healthcheck"
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.adminPath }}/healthcheck"
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: ARLAS_PORT
              value: {{ .Values.containerPort | quote }}
            - name: ARLAS_ADMIN_PATH
              value: {{ .Values.adminPath | quote }}
{{- include "arlas-server.environmentVariables" . | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
